{
  "formatVersion": "1.1",
  "component": {
    "group": "io.fathereye",
    "module": "bridge-api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bridge-api-0.1.0.jar",
          "url": "bridge-api-0.1.0.jar",
          "size": 4420,
          "sha512": "2afb8fc3faa5cef0c9a987ab1791fec2e8a9e6b8aee28e7a6cadf2e0677510bae8379124aaa6635b8a786861c8742ad111df7229625c3fdad9130f180aeb92d3",
          "sha256": "d02d6af4ff88ec8777e5c107722c33f95391e6cf0ed12f387b2e7a91c2fc2ed7",
          "sha1": "423cc62b7ea4914e5b6976393947ff714967ee50",
          "md5": "6f620cef712984d0cec0a8b9430c073e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bridge-api-0.1.0.jar",
          "url": "bridge-api-0.1.0.jar",
          "size": 4420,
          "sha512": "2afb8fc3faa5cef0c9a987ab1791fec2e8a9e6b8aee28e7a6cadf2e0677510bae8379124aaa6635b8a786861c8742ad111df7229625c3fdad9130f180aeb92d3",
          "sha256": "d02d6af4ff88ec8777e5c107722c33f95391e6cf0ed12f387b2e7a91c2fc2ed7",
          "sha1": "423cc62b7ea4914e5b6976393947ff714967ee50",
          "md5": "6f620cef712984d0cec0a8b9430c073e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bridge-api-0.1.0-sources.jar",
          "url": "bridge-api-0.1.0-sources.jar",
          "size": 3267,
          "sha512": "e0efc8cf113600ac93a2036d7d39ca97bc9f4ac0074b14d348009761c679f9672814f560a414666f7e7e3eebe80aca5863effe508c9166225defdeab13c1394f",
          "sha256": "4f26be3d9a5d8ca87e150e51b942b936165a531a7062260ef21378d71b0923de",
          "sha1": "564c5d4715cc76841460408f60c680038fd33792",
          "md5": "ec0a56bd5018d95926ee28389c3a21ba"
        }
      ]
    }
  ]
}
