{
  "formatVersion": "1.1",
  "component": {
    "group": "io.fathereye",
    "module": "mapcore",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mapcore-0.2.0.jar",
          "url": "mapcore-0.2.0.jar",
          "size": 15180,
          "sha512": "ce7853fdaa4d41eee66eeb6e254a1214d7151ca27425a92ca2e0aef242caceec3c7fc66520653c4ce702afb8ab80945ec9d8a316f5bfd4a8c8ca6d1695c9d410",
          "sha256": "2353b49fee8273609d77fb08d4979b582a0d11c65ddc50a8ac961cb696a9e84f",
          "sha1": "9d0acb03dc4ebe23660b66a6cb241eee4f0ca9ae",
          "md5": "7fbd69d9b6821e033b1bbbd79ba76003"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapcore-0.2.0.jar",
          "url": "mapcore-0.2.0.jar",
          "size": 15180,
          "sha512": "ce7853fdaa4d41eee66eeb6e254a1214d7151ca27425a92ca2e0aef242caceec3c7fc66520653c4ce702afb8ab80945ec9d8a316f5bfd4a8c8ca6d1695c9d410",
          "sha256": "2353b49fee8273609d77fb08d4979b582a0d11c65ddc50a8ac961cb696a9e84f",
          "sha1": "9d0acb03dc4ebe23660b66a6cb241eee4f0ca9ae",
          "md5": "7fbd69d9b6821e033b1bbbd79ba76003"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapcore-0.2.0-sources.jar",
          "url": "mapcore-0.2.0-sources.jar",
          "size": 11772,
          "sha512": "d015bc468509a6a95b3a5ea2317b558b58d2265ac4c341caf18b42db6b8324e3fc7bc97261cd8f5c2ab05f2b90aaf0cc83b6210b75a4da9d70e7c83a91f98389",
          "sha256": "4b747d2f1a71a89099b6de3e3a80e6bae7c19d7677003fb5238388bb5c1b064f",
          "sha1": "a79932928ef1ebf169f21114d93dd857dee64e59",
          "md5": "c9852cdc9d753e24824763ef1e865346"
        }
      ]
    }
  ]
}
